version: '3.8'
services:
  web:
    build: ./app
    ports:
      - "8501:8501"
    depends_on:
      - db
    volumes:
      - ./model:/app/model

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
 
